USE [master]
GO

/****** Object:  Database [Basement]    Script Date: 05/09/2017 16:26:32 ******/
CREATE DATABASE [Basement]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Basement', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL11.SQLEXPRESS\MSSQL\DATA\Basement.mdf' , SIZE = 5120KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'Basement_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL11.SQLEXPRESS\MSSQL\DATA\Basement_log.ldf' , SIZE = 2048KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [Basement] SET COMPATIBILITY_LEVEL = 110
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Basement].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Basement] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Basement] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Basement] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Basement] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Basement] SET ARITHABORT OFF 
GO

ALTER DATABASE [Basement] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [Basement] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [Basement] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Basement] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Basement] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Basement] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Basement] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Basement] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Basement] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Basement] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Basement] SET  DISABLE_BROKER 
GO

ALTER DATABASE [Basement] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Basement] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Basement] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Basement] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Basement] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Basement] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Basement] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Basement] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [Basement] SET  MULTI_USER 
GO

ALTER DATABASE [Basement] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Basement] SET DB_CHAINING OFF 
GO

ALTER DATABASE [Basement] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [Basement] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [Basement] SET  READ_WRITE 
GO

